# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-wI-aF_jAtZlL0A_B9q5I3bShX_PHW7_
"""

# -*- coding: utf-8 -*-
"""assignment8.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1pbtVCNlLAs56V7l_orw9ZotBLcxcumQ8
"""
 
# -*- coding: utf-8 -*-
"""Assignment8
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1rAVsfE0ilvTKnilB91FaHLw3yzvMdEQD
"""
 
# -*- coding: utf-8 -*-
"""Assignment-8
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1LzqicnYNu-6UjykStXdWeBn0LInfyN4o
"""
 
import numpy as np
import matplotlib.pyplot as plt
 
#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB
 
#Plotting line 2x-3y > 6
A=np.array([3,0])
B=np.array([0,-2])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='2x-3y>6')
 
#Shading Required Region
x1=[3,0,0,0]
y1=[0,-2,0,0]
plt.fill(x1,y1,color='blue',alpha=0.3)
 
 
#Labelling points
plt.plot(3,0,'o',color='r')
plt.text(3,0,'A(3,0)')
plt.plot(0,0,'o',color='r')
plt.text(0,0,'O(0,0)')
plt.plot(0,-2,'o',color='r')
plt.text(0,-2,'B(0,-2)')
 
plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()